### ISSUE TITLE
Debug mode problem about the cmake branch

### ISSUE THREAD

**Issue by xialang2012** [andre-schulz/mvs-texturing#2]
> Debug Assertion Failed!
> Expression: vector subscript out of range.

at https://github.com/andre-schulz/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L144
When I run it on windows on Debug mode. On the other hand, it can works well on Release mode.

The problem of the bvh_tree() function crash comes from https://github.com/nmoehrle/rayint/blob/cuda/libs/acc/bvh_tree.h#L117

**Comment by hushanming** [comment]
Will you solve this problem？@xialang2012  I have encountered the same problem

**Comment by andre-schulz** [comment]
We've identified two bugs that prevent `mvs-texturing` from working with Visual Studio in debug mode.
The first one has been fixed. (See https://github.com/nmoehrle/rayint/commit/c81f3bb19487c3a121fdeb3019f94a51ceb7ad76)
The second is a race condition in [tex::fill_hole()](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_patches.cpp#L112) which we're currently in the process of fixing.
In the meantime, a workaround for the second bug is to comment out the second for-loop parallelization in [tex::generate_texture_patches()](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_patches.cpp#L506).

**Comment by hushanming** [comment]
Thank you for your prompt reply，I will try it.Thank you! By the way,  _texrecon_ running in Windows platform   slower three times than the  Linux platform, I found the problem debugging code on parallel computing part,so what's your view on it?

**Comment by xialang2012** [comment]
Great! Thank you, @andre-schulz
