### ISSUE TITLE
build error on tex

### ISSUE THREAD

**Issue by debuleilei** [andre-schulz/mvs-texturing#6]
hello, I 've  compiled the mve source code with vs2015 x64 ,but when I tried to compile your mvs-texturing source code ,I met  problems ,can you give me some advice ,wish for your reply!

**Comment by andre-schulz** [comment]
Hi @18500864609,

which problems have you encountered?

**Comment by debuleilei** [comment]
Hi,the problem is when I use the CMake-gui to compile the mvs-texturing-cmake, it can find the mve'lib but with error like this:
###   error: could not find git for clone of ext_rayint
then I tried to load this source code by myself ,and change the cmakelist in the elibs folder like this：
externalproject_add(ext_rayint
    PREFIX          ext_rayint
    #GIT_REPOSITORY  https://github.com/nmoehrle/rayint.git
    GIT_TAG         cuda
    UPDATE_COMMAND  ""
    SOURCE_DIR      ${CMAKE_SOURCE_DIR}/elibs/rayint
    CONFIGURE_COMMAND ""
    BUILD_COMMAND   ""
    INSTALL_COMMAND ""
)

#find_package eigen
externalproject_add(ext_eigen
    PREFIX          ext_eigen
    #URL             https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2
    #URL_MD5         9e3bfaaab3db18253cfd87ea697b3ab1
    SOURCE_DIR      ${CMAKE_SOURCE_DIR}/elibs/eigen
    CONFIGURE_COMMAND ""
    BUILD_COMMAND   ""
    INSTALL_COMMAND ""
)
However ,after the (congigue+general ) when I open the vs2015 to compile ,I get error like this ：
it can't get the tex.lib.
so what should I do now? waiting for your advice!

**Comment by debuleilei** [comment]
aha,sorry,I find that I didn't install git on my windows ,after the installion of git ,Now I successfully compile the mvs-texturing.
Later I will use the mesh built by kinectfusion then texture the mesh, and make it in the android platform. Thanks for your reply!

**Comment by andre-schulz** [comment]
That's good news!
I'll close the issue then. If you encounter other problems feel free to reopen or create another issue.
