### ISSUE TITLE
Error: "came out with the code 3" with compile of mve-texturing . 

### ISSUE THREAD

**Issue by Livan89** [andre-schulz/mvs-texturing#8]
I am trying to compile the texturing in my pc, but I have the error MSB6006 "cmd.exe" came out with the code 3. ext_eigen C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Enterprise \ Common7 \ IDE \ VC \ VCTargets \ Microsoft.CppCommon.targets 209

What could he do? Thank you.

**Comment by andre-schulz** [comment]
Since you mention `ext_eigen` might be related to Eigen moving from BitBucket to GitLab (see https://github.com/andre-schulz/mvs-texturing/issues/11#issuecomment-856945920).
Closing this for now, feel free to reopen.
